version: "3.9"
   
services:
  db:
    container_name: db
    image: mongo:5.0.6-focal
    restart: always
    volumes:
      - ./volumes/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  backend:
    container_name: backend
    build: ./
    restart: always
    depends_on:
      - db
    ports:
      - "5000:3000"
    environment:
      - API_KEY=abcdefgh123456789
    
    