name: CI
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run eslint and jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
      - run: npm install
      - run: npx eslint .
      - run: npm run test

  docker:
    name: Create Docker Image
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: maxluetkemeyer/blood-donation-backend:latest